-- Execute uma vez no SQL Editor do Supabase.
-- O login usa a tabela interna auth.users e não requer tabela pública.
-- A tabela abaixo prepara a futura sincronização segura das leituras.

create table if not exists public.meter_readings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  value numeric not null check (value >= 0),
  measured_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (user_id, value, measured_at)
);

alter table public.meter_readings enable row level security;
grant select, insert, delete on public.meter_readings to authenticated;
grant usage, select on sequence public.meter_readings_id_seq to authenticated;

drop policy if exists "Usuários leem as próprias medições" on public.meter_readings;
create policy "Usuários leem as próprias medições"
on public.meter_readings for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Usuários inserem as próprias medições" on public.meter_readings;
create policy "Usuários inserem as próprias medições"
on public.meter_readings for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Usuários excluem as próprias medições" on public.meter_readings;
create policy "Usuários excluem as próprias medições"
on public.meter_readings for delete to authenticated
using ((select auth.uid()) = user_id);

create index if not exists meter_readings_user_id_idx
on public.meter_readings (user_id);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  rate numeric not null default 0.894560 check (rate > 0),
  goal numeric not null default 250 check (goal > 0),
  flag text not null default 'yellow' check (flag in ('green', 'yellow', 'red1', 'red2')),
  lighting_fee numeric not null default 32 check (lighting_fee >= 0),
  updated_at timestamptz not null default now()
);

alter table public.user_settings enable row level security;
grant select, insert, update on public.user_settings to authenticated;

drop policy if exists "Usuários leem as próprias preferências" on public.user_settings;
create policy "Usuários leem as próprias preferências"
on public.user_settings for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Usuários criam as próprias preferências" on public.user_settings;
create policy "Usuários criam as próprias preferências"
on public.user_settings for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Usuários alteram as próprias preferências" on public.user_settings;
create policy "Usuários alteram as próprias preferências"
on public.user_settings for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
