-- Execute uma vez no SQL Editor do Supabase.
-- O login usa a tabela interna auth.users e não requer tabela pública.
-- A tabela abaixo prepara a futura sincronização segura das leituras.

create table if not exists public.meter_readings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  value numeric not null check (value >= 0),
  measured_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (user_id, value, measured_at)
);

alter table public.meter_readings enable row level security;
grant select, insert, delete on public.meter_readings to authenticated;
grant usage, select on sequence public.meter_readings_id_seq to authenticated;

drop policy if exists "Usuários leem as próprias medições" on public.meter_readings;
create policy "Usuários leem as próprias medições"
on public.meter_readings for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Usuários inserem as próprias medições" on public.meter_readings;
create policy "Usuários inserem as próprias medições"
on public.meter_readings for insert to authenticated
with check ((select auth.uid()) = user_id);

create table if not exists public.water_readings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  value numeric not null check (value >= 0), measured_at timestamptz not null,
  created_at timestamptz not null default now(), unique (user_id, value, measured_at)
);
alter table public.water_readings enable row level security;
grant select, insert, delete on public.water_readings to authenticated;
grant usage, select on sequence public.water_readings_id_seq to authenticated;
drop policy if exists "water_select_own" on public.water_readings;
create policy "water_select_own" on public.water_readings for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "water_insert_own" on public.water_readings;
create policy "water_insert_own" on public.water_readings for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "water_delete_own" on public.water_readings;
create policy "water_delete_own" on public.water_readings for delete to authenticated using ((select auth.uid()) = user_id);

create table if not exists public.water_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  rate numeric not null default 8 check (rate >= 0), goal numeric not null default 15 check (goal > 0),
  sewer_percent numeric not null default 100 check (sewer_percent >= 0),
  fixed_fee numeric not null default 0 check (fixed_fee >= 0), updated_at timestamptz not null default now()
);
alter table public.water_settings enable row level security;
grant select, insert, update on public.water_settings to authenticated;
drop policy if exists "water_settings_select_own" on public.water_settings;
create policy "water_settings_select_own" on public.water_settings for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "water_settings_insert_own" on public.water_settings;
create policy "water_settings_insert_own" on public.water_settings for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "water_settings_update_own" on public.water_settings;
create policy "water_settings_update_own" on public.water_settings for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Usuários excluem as próprias medições" on public.meter_readings;
create policy "Usuários excluem as próprias medições"
on public.meter_readings for delete to authenticated
using ((select auth.uid()) = user_id);

create index if not exists meter_readings_user_id_idx
on public.meter_readings (user_id);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  rate numeric not null default 0.894560 check (rate > 0),
  goal numeric not null default 250 check (goal > 0),
  flag text not null default 'yellow' check (flag in ('green', 'yellow', 'red1', 'red2')),
  lighting_fee numeric not null default 32 check (lighting_fee >= 0),
  updated_at timestamptz not null default now()
);

alter table public.user_settings enable row level security;
grant select, insert, update on public.user_settings to authenticated;

drop policy if exists "Usuários leem as próprias preferências" on public.user_settings;
create policy "Usuários leem as próprias preferências"
on public.user_settings for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Usuários criam as próprias preferências" on public.user_settings;
create policy "Usuários criam as próprias preferências"
on public.user_settings for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Usuários alteram as próprias preferências" on public.user_settings;
create policy "Usuários alteram as próprias preferências"
on public.user_settings for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- LGPD-002: aceite versionado do aviso de privacidade.
-- Append-only para o usuário; correções administrativas devem gerar novo registro.
create table if not exists public.privacy_acceptances (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  notice_version text not null,
  accepted_at timestamptz not null,
  channel text not null check (channel in ('web_signup', 'migration')),
  recorded_at timestamptz not null default now(),
  unique (user_id, notice_version)
);

alter table public.privacy_acceptances enable row level security;
grant select, insert on public.privacy_acceptances to authenticated;

drop policy if exists "privacy_acceptances_select_own" on public.privacy_acceptances;
create policy "privacy_acceptances_select_own"
on public.privacy_acceptances for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "privacy_acceptances_insert_own" on public.privacy_acceptances;
create policy "privacy_acceptances_insert_own"
on public.privacy_acceptances for insert to authenticated
with check ((select auth.uid()) = user_id);

-- LGPD-002 / PRD-016-RF-041: protocolo mínimo de solicitações do titular.
-- O titular cria e consulta; somente operação privilegiada altera o status.
create table if not exists public.data_subject_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  request_type text not null check (request_type in (
    'confirmation', 'access', 'correction', 'portability',
    'anonymization', 'deletion', 'opposition'
  )),
  status text not null default 'requested' check (status in (
    'requested', 'identity_verified', 'in_progress', 'completed', 'partially_denied', 'denied', 'cancelled'
  )),
  privacy_notice_version text not null,
  requested_at timestamptz not null default now(),
  completed_at timestamptz,
  check (completed_at is null or completed_at >= requested_at)
);

alter table public.data_subject_requests enable row level security;
grant select, insert on public.data_subject_requests to authenticated;

drop policy if exists "data_subject_requests_select_own" on public.data_subject_requests;
create policy "data_subject_requests_select_own"
on public.data_subject_requests for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "data_subject_requests_insert_own" on public.data_subject_requests;
create policy "data_subject_requests_insert_own"
on public.data_subject_requests for insert to authenticated
with check ((select auth.uid()) = user_id and status = 'requested');

create index if not exists data_subject_requests_user_requested_idx
on public.data_subject_requests (user_id, requested_at desc);

-- PRD-002: trilha append-only de eventos de segurança visíveis ao titular.
create table if not exists public.auth_security_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('password_changed', 'mfa_changed', 'sessions_revoked')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.beta_password_recovery_requests (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'claimed', 'used', 'revoked')),
  expires_at timestamptz not null,
  claimed_at timestamptz,
  used_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists beta_password_recovery_user_created_idx
on public.beta_password_recovery_requests (user_id, created_at desc);
alter table public.beta_password_recovery_requests enable row level security;
alter table public.beta_password_recovery_requests force row level security;
revoke all on public.beta_password_recovery_requests from public, anon, authenticated;

create or replace function public.beta_password_recovery_request(p_email text, p_request_id uuid)
returns boolean language plpgsql security definer set search_path = '' as $$
declare target_user uuid;
begin
  select u.id into target_user from auth.users u
  where lower(u.email) = lower(trim(p_email)) and u.deleted_at is null
  order by u.created_at limit 1;
  if target_user is null then return false; end if;
  update public.beta_password_recovery_requests
  set status = 'revoked'
  where user_id = target_user and status in ('pending', 'claimed');
  insert into public.beta_password_recovery_requests (id, user_id, expires_at)
  values (p_request_id, target_user, now() + interval '1 hour');
  return true;
end $$;

create or replace function public.beta_password_recovery_claim(p_request_id uuid, p_user_id uuid)
returns boolean language plpgsql security definer set search_path = '' as $$
declare claimed uuid;
begin
  update public.beta_password_recovery_requests
  set status = 'claimed', claimed_at = now()
  where id = p_request_id and user_id = p_user_id and status = 'pending' and expires_at > now()
  returning id into claimed;
  return claimed is not null;
end $$;

create or replace function public.beta_password_recovery_release(p_request_id uuid, p_user_id uuid)
returns void language sql security definer set search_path = '' as $$
  update public.beta_password_recovery_requests
  set status = 'pending', claimed_at = null
  where id = p_request_id and user_id = p_user_id and status = 'claimed' and expires_at > now()
$$;

create or replace function public.beta_password_recovery_finalize(p_request_id uuid, p_user_id uuid)
returns boolean language plpgsql security definer set search_path = '' as $$
declare finalized uuid;
begin
  update public.beta_password_recovery_requests
  set status = 'used', used_at = now()
  where id = p_request_id and user_id = p_user_id and status = 'claimed'
  returning id into finalized;
  if finalized is null then return false; end if;
  insert into public.auth_security_events (user_id, event_type, details) values
    (p_user_id, 'password_changed', jsonb_build_object('method', 'recovery', 'request_id', p_request_id)),
    (p_user_id, 'sessions_revoked', jsonb_build_object('reason', 'password_recovery', 'request_id', p_request_id));
  return true;
end $$;

revoke all on function public.beta_password_recovery_request(text, uuid),
  public.beta_password_recovery_claim(uuid, uuid),
  public.beta_password_recovery_release(uuid, uuid),
  public.beta_password_recovery_finalize(uuid, uuid)
from public, anon, authenticated;
grant execute on function public.beta_password_recovery_request(text, uuid),
  public.beta_password_recovery_claim(uuid, uuid),
  public.beta_password_recovery_release(uuid, uuid),
  public.beta_password_recovery_finalize(uuid, uuid)
to service_role;

create table if not exists public.beta_mfa_backup_codes (
  user_id uuid not null references auth.users(id) on delete cascade,
  code_hash text not null check (code_hash ~ '^[0-9a-f]{64}$'),
  used_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (user_id, code_hash)
);
create table if not exists public.beta_mfa_backup_attempts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  failed_count smallint not null default 0 check (failed_count between 0 and 5),
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.beta_mfa_backup_codes enable row level security;
alter table public.beta_mfa_backup_codes force row level security;
alter table public.beta_mfa_backup_attempts enable row level security;
alter table public.beta_mfa_backup_attempts force row level security;
revoke all on public.beta_mfa_backup_codes, public.beta_mfa_backup_attempts from public, anon, authenticated;

create or replace function public.beta_mfa_backup_replace(p_user_id uuid, p_code_hashes text[])
returns void language plpgsql security definer set search_path = '' as $$
begin
  if p_user_id is null or coalesce(array_length(p_code_hashes, 1), 0) <> 10 then raise exception 'invalid_backup_codes'; end if;
  if exists (select 1 from unnest(p_code_hashes) h where h !~ '^[0-9a-f]{64}$') then raise exception 'invalid_backup_codes'; end if;
  delete from public.beta_mfa_backup_codes where user_id = p_user_id;
  insert into public.beta_mfa_backup_codes (user_id, code_hash)
  select p_user_id, h from unnest(p_code_hashes) h;
  insert into public.beta_mfa_backup_attempts (user_id, failed_count, blocked_until)
  values (p_user_id, 0, null)
  on conflict (user_id) do update set failed_count = 0, blocked_until = null, updated_at = now();
  insert into public.auth_security_events (user_id, event_type, details)
  values (p_user_id, 'mfa_changed', jsonb_build_object('action', 'backup_codes_generated', 'count', 10));
end $$;

create or replace function public.beta_mfa_backup_consume(p_user_id uuid, p_code_hash text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare attempt public.beta_mfa_backup_attempts; matched_hash text; failures integer;
begin
  insert into public.beta_mfa_backup_attempts (user_id) values (p_user_id) on conflict (user_id) do nothing;
  select * into attempt from public.beta_mfa_backup_attempts where user_id = p_user_id for update;
  if attempt.blocked_until is not null and attempt.blocked_until > now() then
    return jsonb_build_object('accepted', false, 'blocked', true, 'retry_after_seconds', greatest(1, ceil(extract(epoch from (attempt.blocked_until - now())))::integer));
  end if;
  select code_hash into matched_hash from public.beta_mfa_backup_codes
  where user_id = p_user_id and code_hash = p_code_hash and used_at is null for update;
  if matched_hash is not null then
    update public.beta_mfa_backup_codes set used_at = now() where user_id = p_user_id and code_hash = matched_hash;
    update public.beta_mfa_backup_attempts set failed_count = 0, blocked_until = null, updated_at = now() where user_id = p_user_id;
    insert into public.auth_security_events (user_id, event_type, details)
    values (p_user_id, 'mfa_changed', jsonb_build_object('action', 'backup_code_used', 'factor_reset_required', true));
    return jsonb_build_object('accepted', true, 'blocked', false, 'remaining_codes', (select count(*) from public.beta_mfa_backup_codes where user_id = p_user_id and used_at is null));
  end if;
  failures := least(5, attempt.failed_count + 1);
  update public.beta_mfa_backup_attempts set failed_count = failures,
    blocked_until = case when failures >= 5 then now() + interval '15 minutes' else null end,
    updated_at = now() where user_id = p_user_id;
  return jsonb_build_object('accepted', false, 'blocked', failures >= 5, 'attempts_remaining', greatest(0, 5 - failures), 'retry_after_seconds', case when failures >= 5 then 900 else 0 end);
end $$;

revoke all on function public.beta_mfa_backup_replace(uuid, text[]), public.beta_mfa_backup_consume(uuid, text) from public, anon, authenticated;
grant execute on function public.beta_mfa_backup_replace(uuid, text[]), public.beta_mfa_backup_consume(uuid, text) to service_role;

alter table public.auth_security_events enable row level security;
grant select, insert on public.auth_security_events to authenticated;
drop policy if exists "auth_security_events_select_own" on public.auth_security_events;
create policy "auth_security_events_select_own" on public.auth_security_events
for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "auth_security_events_insert_own" on public.auth_security_events;
create policy "auth_security_events_insert_own" on public.auth_security_events
for insert to authenticated with check ((select auth.uid()) = user_id);

-- PRD-020 / OBS-001: telemetria mínima, sem conteúdo de leitura ou dado pessoal.
create table if not exists public.operational_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  correlation_id uuid not null,
  event_type text not null check (event_type in ('session.started', 'health.checked', 'runtime.error', 'operation.failed')),
  severity text not null check (severity in ('info', 'warning', 'error')),
  component text not null check (char_length(component) between 2 and 60),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.operational_events add column if not exists trace_id text check (trace_id is null or trace_id ~ '^[0-9a-f]{32}$');
alter table public.operational_events add column if not exists span_id text check (span_id is null or span_id ~ '^[0-9a-f]{16}$');
alter table public.operational_events add column if not exists parent_span_id text check (parent_span_id is null or parent_span_id ~ '^[0-9a-f]{16}$');
alter table public.operational_events enable row level security;
grant insert on public.operational_events to authenticated;
grant usage, select on sequence public.operational_events_id_seq to authenticated;
drop policy if exists "operational_events_insert_own" on public.operational_events;
create policy "operational_events_insert_own" on public.operational_events
for insert to authenticated with check ((select auth.uid()) = user_id);

-- VOLT BETA: compartilha auth.users, mas mantém dados operacionais isolados.
create table if not exists public.beta_meter_readings
(like public.meter_readings including all);
create table if not exists public.beta_water_readings
(like public.water_readings including all);
create table if not exists public.beta_user_settings
(like public.user_settings including all);
create table if not exists public.beta_water_settings
(like public.water_settings including all);
create table if not exists public.beta_privacy_acceptances
(like public.privacy_acceptances including all);
create table if not exists public.beta_data_subject_requests
(like public.data_subject_requests including all);
create table if not exists public.beta_auth_security_events
(like public.auth_security_events including all);
create table if not exists public.beta_operational_events
(like public.operational_events including all);
alter table public.beta_operational_events add column if not exists trace_id text check (trace_id is null or trace_id ~ '^[0-9a-f]{32}$');
alter table public.beta_operational_events add column if not exists span_id text check (span_id is null or span_id ~ '^[0-9a-f]{16}$');
alter table public.beta_operational_events add column if not exists parent_span_id text check (parent_span_id is null or parent_span_id ~ '^[0-9a-f]{16}$');

-- Alertas operacionais derivados no banco em tempo real. O payload deliberadamente
-- nÃ£o replica details nem identificadores pessoais do evento de origem.
create table if not exists public.beta_operational_alerts (
  id bigint generated by default as identity primary key,
  source_event_id bigint not null unique references public.beta_operational_events(id) on delete cascade,
  rule_key text not null check (rule_key in ('runtime-error', 'operation-failed', 'high-latency')),
  severity text not null check (severity in ('warning', 'critical')),
  component text not null check (char_length(component) between 2 and 60),
  status text not null default 'firing' check (status in ('firing', 'acknowledged')),
  fired_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  acknowledged_by uuid references auth.users(id),
  acknowledgement_reason text,
  check ((status = 'firing' and acknowledged_at is null and acknowledged_by is null and acknowledgement_reason is null)
    or (status = 'acknowledged' and acknowledged_at is not null and acknowledged_by is not null and char_length(acknowledgement_reason) between 10 and 500))
);

create or replace function public.beta_raise_operational_alert()
returns trigger language plpgsql security definer set search_path = '' as $$
declare rule text; alert_severity text;
begin
  if new.severity = 'error' and new.event_type = 'runtime.error' then
    rule := 'runtime-error'; alert_severity := 'critical';
  elsif new.severity = 'error' and new.event_type = 'operation.failed' then
    rule := 'operation-failed'; alert_severity := 'critical';
  elsif coalesce(new.duration_ms, 0) >= 2000 then
    rule := 'high-latency'; alert_severity := 'warning';
  else
    return new;
  end if;
  insert into public.beta_operational_alerts (source_event_id, rule_key, severity, component, fired_at)
  values (new.id, rule, alert_severity, new.component, clock_timestamp())
  on conflict (source_event_id) do nothing;
  return new;
end $$;

drop trigger if exists beta_operational_alert_trigger on public.beta_operational_events;
create trigger beta_operational_alert_trigger
after insert on public.beta_operational_events
for each row execute function public.beta_raise_operational_alert();

do $$
declare
  beta_table text;
begin
  foreach beta_table in array array[
    'beta_meter_readings', 'beta_water_readings', 'beta_user_settings',
    'beta_water_settings', 'beta_privacy_acceptances', 'beta_data_subject_requests',
    'beta_auth_security_events', 'beta_operational_events'
  ] loop
    if not exists (
      select 1 from pg_constraint
      where conname = beta_table || '_user_id_fkey'
        and conrelid = ('public.' || beta_table)::regclass
    ) then
      execute format(
        'alter table public.%I add constraint %I foreign key (user_id) references auth.users(id) on delete cascade',
        beta_table,
        beta_table || '_user_id_fkey'
      );
    end if;
  end loop;
end $$;

alter table public.beta_meter_readings enable row level security;
alter table public.beta_water_readings enable row level security;
alter table public.beta_user_settings enable row level security;
alter table public.beta_water_settings enable row level security;
alter table public.beta_privacy_acceptances enable row level security;
alter table public.beta_data_subject_requests enable row level security;
alter table public.beta_auth_security_events enable row level security;
alter table public.beta_operational_events enable row level security;
alter table public.beta_operational_alerts enable row level security;
alter table public.beta_operational_alerts force row level security;

grant select, insert, update, delete on public.beta_meter_readings, public.beta_water_readings to authenticated;
grant select, insert, update on public.beta_user_settings, public.beta_water_settings to authenticated;
grant select, insert on public.beta_privacy_acceptances, public.beta_data_subject_requests, public.beta_auth_security_events to authenticated;
grant insert on public.beta_operational_events to authenticated;
grant usage, select on sequence public.beta_meter_readings_id_seq, public.beta_water_readings_id_seq to authenticated;
grant usage, select on sequence public.beta_operational_events_id_seq to authenticated;

drop policy if exists "beta_meter_readings_select_own" on public.beta_meter_readings;
create policy "beta_meter_readings_select_own" on public.beta_meter_readings
for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "beta_meter_readings_insert_own" on public.beta_meter_readings;
create policy "beta_meter_readings_insert_own" on public.beta_meter_readings
for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "beta_meter_readings_update_own" on public.beta_meter_readings;
create policy "beta_meter_readings_update_own" on public.beta_meter_readings
for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "beta_meter_readings_delete_own" on public.beta_meter_readings;
create policy "beta_meter_readings_delete_own" on public.beta_meter_readings
for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "beta_water_readings_select_own" on public.beta_water_readings;
create policy "beta_water_readings_select_own" on public.beta_water_readings
for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "beta_water_readings_insert_own" on public.beta_water_readings;
create policy "beta_water_readings_insert_own" on public.beta_water_readings
for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "beta_water_readings_update_own" on public.beta_water_readings;
create policy "beta_water_readings_update_own" on public.beta_water_readings
for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "beta_water_readings_delete_own" on public.beta_water_readings;
create policy "beta_water_readings_delete_own" on public.beta_water_readings
for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "beta_user_settings_select_own" on public.beta_user_settings;
create policy "beta_user_settings_select_own" on public.beta_user_settings
for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "beta_user_settings_insert_own" on public.beta_user_settings;
create policy "beta_user_settings_insert_own" on public.beta_user_settings
for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "beta_user_settings_update_own" on public.beta_user_settings;
create policy "beta_user_settings_update_own" on public.beta_user_settings
for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "beta_water_settings_select_own" on public.beta_water_settings;
create policy "beta_water_settings_select_own" on public.beta_water_settings
for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "beta_water_settings_insert_own" on public.beta_water_settings;
create policy "beta_water_settings_insert_own" on public.beta_water_settings
for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "beta_water_settings_update_own" on public.beta_water_settings;
create policy "beta_water_settings_update_own" on public.beta_water_settings
for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "beta_privacy_acceptances_select_own" on public.beta_privacy_acceptances;
create policy "beta_privacy_acceptances_select_own" on public.beta_privacy_acceptances
for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "beta_privacy_acceptances_insert_own" on public.beta_privacy_acceptances;
create policy "beta_privacy_acceptances_insert_own" on public.beta_privacy_acceptances
for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "beta_data_subject_requests_select_own" on public.beta_data_subject_requests;
create policy "beta_data_subject_requests_select_own" on public.beta_data_subject_requests
for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "beta_data_subject_requests_insert_own" on public.beta_data_subject_requests;
create policy "beta_data_subject_requests_insert_own" on public.beta_data_subject_requests
for insert to authenticated with check ((select auth.uid()) = user_id and status = 'requested');

drop policy if exists "beta_auth_security_events_select_own" on public.beta_auth_security_events;
create policy "beta_auth_security_events_select_own" on public.beta_auth_security_events
for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "beta_auth_security_events_insert_own" on public.beta_auth_security_events;
create policy "beta_auth_security_events_insert_own" on public.beta_auth_security_events
for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "beta_operational_events_insert_own" on public.beta_operational_events;
create policy "beta_operational_events_insert_own" on public.beta_operational_events
for insert to authenticated with check ((select auth.uid()) = user_id);

create index if not exists beta_meter_readings_user_id_idx
on public.beta_meter_readings (user_id);
create index if not exists beta_data_subject_requests_user_requested_idx
on public.beta_data_subject_requests (user_id, requested_at desc);

-- Administração segura da organização na Beta (PRD-003/004/005).
create table if not exists public.beta_organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 80),
  owner_user_id uuid not null references auth.users(id),
  status text not null default 'active' check (status in ('active', 'suspended', 'archived')),
  created_at timestamptz not null default now()
);

create table if not exists public.beta_memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.beta_organizations(id),
  user_id uuid not null references auth.users(id),
  email text not null,
  display_name text not null,
  role text not null check (role in ('owner', 'admin', 'member', 'viewer')),
  status text not null default 'active' check (status in ('active', 'suspended', 'removed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create table if not exists public.beta_invitations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.beta_organizations(id),
  email text not null,
  role text not null check (role in ('admin', 'member', 'viewer')),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'revoked', 'expired')),
  invited_by uuid not null references auth.users(id),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.beta_invitations add column if not exists token_hash text;
alter table public.beta_invitations add column if not exists consumed_at timestamptz;
alter table public.beta_invitations add column if not exists declined_at timestamptz;
alter table public.beta_invitations drop constraint if exists beta_invitations_status_check;
alter table public.beta_invitations add constraint beta_invitations_status_check
check (status in ('pending', 'accepted', 'declined', 'revoked', 'expired'));
update public.beta_invitations set status = 'revoked'
where status = 'pending' and token_hash is null;
alter table public.beta_invitations drop constraint if exists beta_invitations_pending_token_check;
alter table public.beta_invitations add constraint beta_invitations_pending_token_check
check (status <> 'pending' or token_hash is not null);
create unique index if not exists beta_invitations_token_hash_idx
on public.beta_invitations (token_hash) where token_hash is not null;

create table if not exists public.beta_admin_audit (
  id bigint generated always as identity primary key,
  organization_id uuid not null references public.beta_organizations(id),
  actor_user_id uuid not null references auth.users(id),
  action text not null,
  target_id uuid,
  reason text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.beta_feature_flags (
  key text primary key check (key ~ '^[a-z][a-z0-9._-]{2,79}$'),
  description text not null check (char_length(description) between 3 and 160),
  enabled boolean not null default false,
  rollout_percentage smallint not null default 0 check (rollout_percentage between 0 and 100),
  kill_switch boolean not null default false,
  user_ids uuid[] not null default '{}',
  tenant_ids uuid[] not null default '{}',
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

insert into public.beta_feature_flags (key, description, enabled, rollout_percentage)
values
  ('identity.new-auth', 'Novo fluxo de autenticação BFF', false, 0),
  ('engines.rule', 'Motor de regras do consumo', true, 100),
  ('engines.calculation', 'Motor de cálculo do consumo', true, 100),
  ('experimental.ocr', 'Reconhecimento local de leituras', false, 0),
  ('experimental.ai', 'Copiloto de inteligência artificial', false, 0),
  ('experimental.dashboard', 'Dashboard analítico avançado', false, 0),
  ('experimental.integrations', 'Hub de integrações', false, 0)
on conflict (key) do nothing;

-- Contexto ativo separa o tenant da identidade e permite evoluir para múltiplas
-- organizações sem confiar em organization_id enviado pelo navegador.
create table if not exists public.beta_user_context (
  user_id uuid primary key references auth.users(id) on delete cascade,
  organization_id uuid not null references public.beta_organizations(id),
  updated_at timestamptz not null default now()
);

alter table public.beta_organizations enable row level security;
alter table public.beta_memberships enable row level security;
alter table public.beta_invitations enable row level security;
alter table public.beta_admin_audit enable row level security;
alter table public.beta_feature_flags enable row level security;
alter table public.beta_user_context enable row level security;
alter table public.beta_feature_flags force row level security;
revoke all on public.beta_organizations, public.beta_memberships, public.beta_invitations, public.beta_admin_audit, public.beta_feature_flags, public.beta_user_context from anon, authenticated;

-- Dual-write da identidade: auth.users continua sendo a fonte das credenciais e
-- cada identidade ganha, de forma idempotente, organização, membership e contexto.
-- Nenhuma senha ou token é copiado para o schema público.
create or replace function public.beta_provision_identity(
  p_user_id uuid,
  p_email text,
  p_display_name text default null
)
returns uuid language plpgsql security definer set search_path = '' as $$
declare
  target_organization uuid;
  safe_email text := lower(trim(coalesce(p_email, '')));
  safe_name text := left(trim(coalesce(p_display_name, '')), 80);
begin
  if p_user_id is null then raise exception 'user_required'; end if;
  if safe_email = '' then safe_email := p_user_id::text || '@pending.volt'; end if;
  if safe_name = '' then safe_name := split_part(safe_email, '@', 1); end if;

  select m.organization_id into target_organization
  from public.beta_memberships m
  where m.user_id = p_user_id and m.status = 'active'
  order by m.created_at, m.id limit 1;

  if target_organization is null then
    insert into public.beta_organizations (name, owner_user_id)
    values ('Minha organização', p_user_id)
    returning id into target_organization;
    insert into public.beta_memberships (organization_id, user_id, email, display_name, role)
    values (target_organization, p_user_id, safe_email, safe_name, 'owner');
  else
    update public.beta_memberships
    set email = safe_email,
        display_name = case when display_name in ('Usuário migrado', '') then safe_name else display_name end,
        updated_at = now()
    where organization_id = target_organization and user_id = p_user_id;
  end if;

  insert into public.beta_user_context (user_id, organization_id)
  values (p_user_id, target_organization)
  on conflict (user_id) do update
  set organization_id = case
    when exists (
      select 1 from public.beta_memberships m
      where m.user_id = p_user_id and m.organization_id = public.beta_user_context.organization_id and m.status = 'active'
    ) then public.beta_user_context.organization_id
    else excluded.organization_id
  end,
  updated_at = now();
  return target_organization;
end $$;

create or replace function public.beta_auth_user_dual_write()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  perform public.beta_provision_identity(
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'name')
  );
  return new;
end $$;

drop trigger if exists beta_auth_user_dual_write on auth.users;
create trigger beta_auth_user_dual_write
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.beta_auth_user_dual_write();

revoke all on function public.beta_provision_identity(uuid, text, text), public.beta_auth_user_dual_write() from public, anon, authenticated;

-- Expand/contract: cria uma organização determinística para cada usuário
-- legado que ainda não possua membership e preserva todas as linhas existentes.
alter table public.beta_meter_readings add column if not exists organization_id uuid references public.beta_organizations(id);
alter table public.beta_water_readings add column if not exists organization_id uuid references public.beta_organizations(id);
alter table public.beta_user_settings add column if not exists organization_id uuid references public.beta_organizations(id);
alter table public.beta_water_settings add column if not exists organization_id uuid references public.beta_organizations(id);

do $$
declare legacy_user uuid; legacy_email text; legacy_name text;
begin
  for legacy_user, legacy_email, legacy_name in
    select u.id, u.email, coalesce(u.raw_user_meta_data ->> 'display_name', u.raw_user_meta_data ->> 'name')
    from auth.users u
  loop
    perform public.beta_provision_identity(legacy_user, legacy_email, legacy_name);
  end loop;
end $$;

create or replace function public.beta_identity_migration_integrity()
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'auth_users', (select count(*) from auth.users),
    'users_with_active_membership', (select count(distinct user_id) from public.beta_memberships where status = 'active'),
    'users_with_context', (select count(*) from public.beta_user_context),
    'missing_membership', (
      select count(*) from auth.users u where not exists (
        select 1 from public.beta_memberships m where m.user_id = u.id and m.status = 'active'
      )
    ),
    'missing_context', (
      select count(*) from auth.users u where not exists (
        select 1 from public.beta_user_context c where c.user_id = u.id
      )
    ),
    'invalid_context', (
      select count(*) from public.beta_user_context c where not exists (
        select 1 from public.beta_memberships m
        where m.user_id = c.user_id and m.organization_id = c.organization_id and m.status = 'active'
      )
    )
  )
$$;
revoke all on function public.beta_identity_migration_integrity() from public, anon, authenticated;

insert into public.beta_user_context (user_id, organization_id)
select distinct on (user_id) user_id, organization_id
from public.beta_memberships where status = 'active'
order by user_id, created_at
on conflict (user_id) do nothing;

update public.beta_meter_readings r set organization_id = c.organization_id from public.beta_user_context c where r.user_id = c.user_id and r.organization_id is null;
update public.beta_water_readings r set organization_id = c.organization_id from public.beta_user_context c where r.user_id = c.user_id and r.organization_id is null;
update public.beta_user_settings r set organization_id = c.organization_id from public.beta_user_context c where r.user_id = c.user_id and r.organization_id is null;
update public.beta_water_settings r set organization_id = c.organization_id from public.beta_user_context c where r.user_id = c.user_id and r.organization_id is null;

alter table public.beta_meter_readings alter column organization_id set not null;
alter table public.beta_water_readings alter column organization_id set not null;
alter table public.beta_user_settings alter column organization_id set not null;
alter table public.beta_water_settings alter column organization_id set not null;
alter table public.beta_meter_readings force row level security;
alter table public.beta_water_readings force row level security;
alter table public.beta_user_settings force row level security;
alter table public.beta_water_settings force row level security;

create index if not exists beta_meter_readings_organization_idx on public.beta_meter_readings (organization_id, measured_at desc);
create index if not exists beta_water_readings_organization_idx on public.beta_water_readings (organization_id, measured_at desc);
create index if not exists beta_user_settings_organization_idx on public.beta_user_settings (organization_id);
create index if not exists beta_water_settings_organization_idx on public.beta_water_settings (organization_id);
create index if not exists beta_memberships_user_status_idx on public.beta_memberships (user_id, status);
create unique index if not exists beta_memberships_one_active_owner_idx
on public.beta_memberships (organization_id) where role = 'owner' and status = 'active';

create or replace function public.beta_enforce_owner_invariant()
returns trigger language plpgsql security definer set search_path = '' as $$
declare affected_organization uuid := coalesce(new.organization_id, old.organization_id); owner_count integer;
begin
  select count(*) into owner_count from public.beta_memberships
  where organization_id = affected_organization and role = 'owner' and status = 'active';
  if owner_count <> 1 then raise exception 'owner_invariant'; end if;
  return coalesce(new, old);
end $$;

drop trigger if exists beta_memberships_owner_invariant on public.beta_memberships;
create constraint trigger beta_memberships_owner_invariant
after insert or update or delete on public.beta_memberships
deferrable initially deferred for each row execute function public.beta_enforce_owner_invariant();
revoke all on function public.beta_enforce_owner_invariant() from public, anon, authenticated;

create or replace function public.beta_current_organization()
returns uuid language sql stable security definer set search_path = '' as $$
  select c.organization_id
  from public.beta_user_context c
  join public.beta_memberships m on m.organization_id = c.organization_id and m.user_id = c.user_id
  join public.beta_organizations o on o.id = c.organization_id
  where c.user_id = auth.uid() and m.status = 'active' and o.status = 'active'
$$;

create or replace function public.beta_current_role()
returns text language sql stable security definer set search_path = '' as $$
  select m.role
  from public.beta_user_context c
  join public.beta_memberships m on m.organization_id = c.organization_id and m.user_id = c.user_id
  where c.user_id = auth.uid() and m.status = 'active'
$$;

create or replace function public.beta_assign_organization()
returns trigger language plpgsql security definer set search_path = '' as $$
declare current_organization uuid := public.beta_current_organization();
begin
  if current_organization is null then raise exception 'organization_context_required'; end if;
  if new.organization_id is not null and new.organization_id <> current_organization then raise exception 'organization_context_mismatch'; end if;
  new.organization_id := current_organization;
  new.user_id := auth.uid();
  return new;
end $$;

do $$ declare beta_table text;
begin
  foreach beta_table in array array['beta_meter_readings', 'beta_water_readings', 'beta_user_settings', 'beta_water_settings'] loop
    execute format('drop trigger if exists beta_assign_organization on public.%I', beta_table);
    execute format('create trigger beta_assign_organization before insert on public.%I for each row execute function public.beta_assign_organization()', beta_table);
  end loop;
end $$;

do $$ declare beta_table text; policy_name text;
begin
  foreach beta_table in array array['beta_meter_readings', 'beta_water_readings', 'beta_user_settings', 'beta_water_settings'] loop
    foreach policy_name in array array['select_own', 'insert_own', 'update_own', 'delete_own'] loop
      execute format('drop policy if exists %I on public.%I', beta_table || '_' || policy_name, beta_table);
    end loop;
    execute format('create policy %I on public.%I for select to authenticated using (organization_id = public.beta_current_organization())', beta_table || '_select_tenant', beta_table);
    execute format('create policy %I on public.%I for insert to authenticated with check (organization_id = public.beta_current_organization() and user_id = auth.uid() and public.beta_current_role() in (''owner'', ''admin'', ''member''))', beta_table || '_insert_tenant', beta_table);
    execute format('create policy %I on public.%I for update to authenticated using (organization_id = public.beta_current_organization() and user_id = auth.uid() and public.beta_current_role() in (''owner'', ''admin'', ''member'')) with check (organization_id = public.beta_current_organization() and user_id = auth.uid())', beta_table || '_update_tenant', beta_table);
    if beta_table in ('beta_meter_readings', 'beta_water_readings') then
      execute format('create policy %I on public.%I for delete to authenticated using (organization_id = public.beta_current_organization() and user_id = auth.uid() and public.beta_current_role() in (''owner'', ''admin'', ''member''))', beta_table || '_delete_tenant', beta_table);
    end if;
  end loop;
end $$;

revoke all on function public.beta_current_organization(), public.beta_current_role(), public.beta_assign_organization() from public, anon;
grant execute on function public.beta_current_organization(), public.beta_current_role() to authenticated;

create or replace function public.beta_organization_context()
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'active_organization_id', public.beta_current_organization(),
    'organizations', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', o.id,
        'name', o.name,
        'status', o.status,
        'role', m.role
      ) order by o.name, o.id)
      from public.beta_memberships m
      join public.beta_organizations o on o.id = m.organization_id
      where m.user_id = auth.uid() and m.status = 'active' and o.status = 'active'
    ), '[]'::jsonb)
  )
$$;

create or replace function public.beta_switch_organization(p_organization_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  caller uuid := auth.uid();
  membership public.beta_memberships;
  organization public.beta_organizations;
begin
  if caller is null then raise exception 'authentication_required'; end if;
  select * into membership from public.beta_memberships
  where user_id = caller and organization_id = p_organization_id and status = 'active';
  if not found then raise exception 'membership_required'; end if;
  select * into organization from public.beta_organizations where id = p_organization_id and status = 'active';
  if not found then raise exception 'tenant_inactive'; end if;

  insert into public.beta_user_context (user_id, organization_id)
  values (caller, p_organization_id)
  on conflict (user_id) do update set organization_id = excluded.organization_id, updated_at = now();
  insert into public.beta_admin_audit (organization_id, actor_user_id, action, target_id, reason, details)
  values (p_organization_id, caller, 'context.changed', p_organization_id, 'Troca explícita de organização', jsonb_build_object('role', membership.role));
  return jsonb_build_object('organization_id', organization.id, 'name', organization.name, 'role', membership.role);
end $$;

revoke all on function public.beta_organization_context(), public.beta_switch_organization(uuid) from public, anon;
grant execute on function public.beta_organization_context(), public.beta_switch_organization(uuid) to authenticated;

create or replace function public.beta_admin_bootstrap(p_organization_name text, p_display_name text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  caller uuid := auth.uid();
  caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  existing public.beta_memberships;
  organization_id uuid;
begin
  if caller is null or caller_email = '' then raise exception 'authentication_required'; end if;
  select m.* into existing
  from public.beta_user_context c
  join public.beta_memberships m on m.user_id = c.user_id and m.organization_id = c.organization_id
  join public.beta_organizations o on o.id = c.organization_id
  where c.user_id = caller and m.status = 'active' and o.status = 'active';
  if not found then
    select * into existing from public.beta_memberships where user_id = caller and status = 'active' order by created_at limit 1;
  end if;
  if found then
    update public.beta_memberships
    set email = caller_email, display_name = left(trim(p_display_name), 80), updated_at = now()
    where id = existing.id;
    update public.beta_organizations
    set name = left(trim(p_organization_name), 80)
    where id = existing.organization_id
      and owner_user_id = caller
      and name in ('Minha organização', 'Organização migrada');
    insert into public.beta_user_context (user_id, organization_id)
    values (caller, existing.organization_id)
    on conflict (user_id) do update set organization_id = excluded.organization_id, updated_at = now();
    return jsonb_build_object('membership_id', existing.id, 'organization_id', existing.organization_id);
  end if;

  if caller_email <> 'flanhenriquee@icloud.com' then raise exception 'permission_denied'; end if;

  insert into public.beta_organizations (name, owner_user_id)
  values (left(trim(p_organization_name), 80), caller) returning id into organization_id;
  insert into public.beta_memberships (organization_id, user_id, email, display_name, role)
  values (organization_id, caller, caller_email, left(trim(p_display_name), 80), 'owner') returning id into existing.id;
  insert into public.beta_user_context (user_id, organization_id) values (caller, organization_id)
  on conflict (user_id) do update set organization_id = excluded.organization_id, updated_at = now();
  insert into public.beta_admin_audit (organization_id, actor_user_id, action, target_id, reason)
  values (organization_id, caller, 'organization.created', organization_id, 'Bootstrap seguro da organização Beta');
  return jsonb_build_object('membership_id', existing.id, 'organization_id', organization_id);
end $$;

create or replace function public.beta_admin_snapshot()
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  caller uuid := auth.uid();
  actor public.beta_memberships;
  organization public.beta_organizations;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'flanhenriquee@icloud.com'
     or coalesce(auth.jwt() ->> 'aal', 'aal1') <> 'aal2' then
    return jsonb_build_object('authorized', false);
  end if;
  select m.* into actor from public.beta_memberships m
  join public.beta_user_context c on c.organization_id = m.organization_id and c.user_id = m.user_id
  where m.user_id = caller and m.status = 'active';
  if not found then return jsonb_build_object('authorized', false); end if;
  select * into organization from public.beta_organizations where id = actor.organization_id;
  return jsonb_build_object(
    'authorized', actor.role in ('owner', 'admin'),
    'organization', jsonb_build_object('id', organization.id, 'name', organization.name, 'status', organization.status),
    'membership', jsonb_build_object('id', actor.id, 'role', actor.role, 'status', actor.status),
    'members', case when actor.role in ('owner', 'admin') then (
      select coalesce(jsonb_agg(jsonb_build_object('id', m.id, 'email', m.email, 'display_name', m.display_name, 'role', m.role, 'status', m.status) order by m.created_at), '[]'::jsonb)
      from public.beta_memberships m where m.organization_id = actor.organization_id and m.status <> 'removed'
    ) else '[]'::jsonb end,
    'invitations', case when actor.role in ('owner', 'admin') then (
      select coalesce(jsonb_agg(jsonb_build_object('id', i.id, 'email', i.email, 'role', i.role, 'status', i.status, 'expires_at', i.expires_at) order by i.created_at desc), '[]'::jsonb)
      from public.beta_invitations i where i.organization_id = actor.organization_id and i.status = 'pending' and i.expires_at > now()
    ) else '[]'::jsonb end
  );
end $$;

-- Permissão mínima para o bootstrap. Não carrega diretório, convites, métricas
-- ou flags; esses dados permanecem lazy e são obtidos somente ao abrir Usuários.
create or replace function public.beta_user_permissions()
returns jsonb language sql stable security invoker set search_path = '' as $$
  select jsonb_build_object(
    'role', permission.role,
    'can_manage_users',
      auth.uid() is not null
      and
      lower(coalesce(auth.jwt() ->> 'email', '')) = 'flanhenriquee@icloud.com'
      and coalesce(auth.jwt() ->> 'aal', 'aal1') = 'aal2'
      and permission.role in ('owner', 'admin')
  )
  from (select public.beta_current_role() as role) permission
$$;

drop function if exists public.beta_admin_invite_member(text, text);
create function public.beta_admin_invite_member(p_email text, p_role text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  actor public.beta_memberships;
  invitation_id uuid;
  normalized_email text := lower(trim(p_email));
  invitation_token text := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');
  invitation_hash text := encode(sha256(convert_to(invitation_token, 'UTF8')), 'hex');
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'flanhenriquee@icloud.com'
     or coalesce(auth.jwt() ->> 'aal', 'aal1') <> 'aal2' then raise exception 'permission_denied'; end if;
  select m.* into actor from public.beta_memberships m
  join public.beta_user_context c on c.organization_id = m.organization_id and c.user_id = m.user_id
  where m.user_id = auth.uid() and m.status = 'active';
  if not found or actor.role not in ('owner', 'admin') then raise exception 'permission_denied'; end if;
  if normalized_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then raise exception 'invalid_email'; end if;
  if p_role not in ('admin', 'member', 'viewer') then raise exception 'invalid_role'; end if;
  update public.beta_invitations set status = 'revoked' where organization_id = actor.organization_id and lower(email) = normalized_email and status = 'pending';
  if exists (
    select 1 from public.beta_memberships
    where organization_id = actor.organization_id and lower(email) = normalized_email and status = 'active'
  ) then raise exception 'membership_exists'; end if;
  insert into public.beta_invitations (organization_id, email, role, invited_by, expires_at, token_hash)
  values (actor.organization_id, normalized_email, p_role, auth.uid(), now() + interval '48 hours', invitation_hash) returning id into invitation_id;
  insert into public.beta_admin_audit (organization_id, actor_user_id, action, target_id, reason, details)
  values (actor.organization_id, auth.uid(), 'member.invited', invitation_id, 'Convite administrativo', jsonb_build_object('role', p_role));
  return jsonb_build_object('invitation_id', invitation_id, 'token', invitation_token, 'expires_at', now() + interval '48 hours');
end $$;

create or replace function public.beta_invitation_preview(p_token text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  invitation public.beta_invitations;
  organization public.beta_organizations;
  supplied_hash text;
begin
  if auth.uid() is null or caller_email = '' then raise exception 'authentication_required'; end if;
  if p_token !~ '^[a-f0-9]{64}$' then raise exception 'invalid_invitation'; end if;
  supplied_hash := encode(sha256(convert_to(p_token, 'UTF8')), 'hex');
  select * into invitation from public.beta_invitations where token_hash = supplied_hash;
  if not found or invitation.status <> 'pending' or lower(invitation.email) <> caller_email then raise exception 'invalid_invitation'; end if;
  if invitation.expires_at <= now() then
    update public.beta_invitations set status = 'expired' where id = invitation.id and status = 'pending';
    raise exception 'invite_expired';
  end if;
  select * into organization from public.beta_organizations where id = invitation.organization_id and status = 'active';
  if not found then raise exception 'tenant_inactive'; end if;
  return jsonb_build_object(
    'invitation_id', invitation.id,
    'organization', jsonb_build_object('id', organization.id, 'name', organization.name),
    'role', invitation.role,
    'expires_at', invitation.expires_at
  );
end $$;

create or replace function public.beta_accept_invitation(p_token text, p_display_name text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  caller uuid := auth.uid();
  caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  invitation public.beta_invitations;
  membership_id uuid;
  supplied_hash text;
begin
  if caller is null or caller_email = '' then raise exception 'authentication_required'; end if;
  if p_token !~ '^[a-f0-9]{64}$' then raise exception 'invalid_invitation'; end if;
  supplied_hash := encode(sha256(convert_to(p_token, 'UTF8')), 'hex');
  select * into invitation from public.beta_invitations where token_hash = supplied_hash for update;
  if not found or invitation.status <> 'pending' or lower(invitation.email) <> caller_email then raise exception 'invalid_invitation'; end if;
  if invitation.expires_at <= now() then
    update public.beta_invitations set status = 'expired' where id = invitation.id;
    raise exception 'invite_expired';
  end if;
  if not exists (select 1 from public.beta_organizations where id = invitation.organization_id and status = 'active') then raise exception 'tenant_inactive'; end if;

  insert into public.beta_memberships (organization_id, user_id, email, display_name, role, status)
  values (invitation.organization_id, caller, caller_email, left(trim(p_display_name), 80), invitation.role, 'active')
  on conflict (organization_id, user_id) do update
  set email = excluded.email, display_name = excluded.display_name, role = excluded.role, status = 'active', updated_at = now()
  returning id into membership_id;
  update public.beta_invitations set status = 'accepted', consumed_at = now() where id = invitation.id;
  insert into public.beta_user_context (user_id, organization_id)
  values (caller, invitation.organization_id)
  on conflict (user_id) do update set organization_id = excluded.organization_id, updated_at = now();
  insert into public.beta_admin_audit (organization_id, actor_user_id, action, target_id, reason)
  values (invitation.organization_id, caller, 'invitation.accepted', membership_id, 'Aceite explícito com token de uso único');
  return jsonb_build_object('membership_id', membership_id, 'organization_id', invitation.organization_id);
end $$;

create or replace function public.beta_decline_invitation(p_token text)
returns void language plpgsql security definer set search_path = '' as $$
declare
  caller uuid := auth.uid();
  caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  invitation public.beta_invitations;
  supplied_hash text;
begin
  if caller is null or caller_email = '' then raise exception 'authentication_required'; end if;
  if p_token !~ '^[a-f0-9]{64}$' then raise exception 'invalid_invitation'; end if;
  supplied_hash := encode(sha256(convert_to(p_token, 'UTF8')), 'hex');
  select * into invitation from public.beta_invitations where token_hash = supplied_hash for update;
  if not found or invitation.status <> 'pending' or lower(invitation.email) <> caller_email then raise exception 'invalid_invitation'; end if;
  update public.beta_invitations set status = 'declined', declined_at = now() where id = invitation.id;
  insert into public.beta_admin_audit (organization_id, actor_user_id, action, target_id, reason)
  values (invitation.organization_id, caller, 'invitation.declined', invitation.id, 'Recusa explícita pelo destinatário autenticado');
end $$;

create or replace function public.beta_admin_update_member(p_membership_id uuid, p_role text, p_status text, p_reason text)
returns void language plpgsql security definer set search_path = '' as $$
declare actor public.beta_memberships; target public.beta_memberships;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'flanhenriquee@icloud.com'
     or coalesce(auth.jwt() ->> 'aal', 'aal1') <> 'aal2' then raise exception 'permission_denied'; end if;
  select m.* into actor from public.beta_memberships m
  join public.beta_user_context c on c.organization_id = m.organization_id and c.user_id = m.user_id
  where m.user_id = auth.uid() and m.status = 'active';
  if not found or actor.role not in ('owner', 'admin') then raise exception 'permission_denied'; end if;
  select * into target from public.beta_memberships where id = p_membership_id and organization_id = actor.organization_id for update;
  if not found then raise exception 'permission_denied'; end if;
  if p_role not in ('owner', 'admin', 'member', 'viewer') or p_status not in ('active', 'suspended', 'removed') then raise exception 'invalid_state'; end if;
  if char_length(trim(p_reason)) < 5 then raise exception 'invalid_reason'; end if;
  if actor.role <> 'owner' and (target.role = 'owner' or p_role in ('owner', 'admin')) then raise exception 'permission_denied'; end if;
  if target.role = 'owner' or p_role = 'owner' then raise exception 'use_owner_transfer'; end if;
  update public.beta_memberships set role = p_role, status = p_status, updated_at = now() where id = target.id;
  insert into public.beta_admin_audit (organization_id, actor_user_id, action, target_id, reason, details)
  values (actor.organization_id, auth.uid(), 'member.access_updated', target.id, trim(p_reason), jsonb_build_object('before_role', target.role, 'before_status', target.status, 'after_role', p_role, 'after_status', p_status));
end $$;

create or replace function public.beta_admin_transfer_owner(p_membership_id uuid, p_reason text)
returns void language plpgsql security definer set search_path = '' as $$
declare actor public.beta_memberships; current_owner public.beta_memberships; successor public.beta_memberships;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'flanhenriquee@icloud.com'
     or coalesce(auth.jwt() ->> 'aal', 'aal1') <> 'aal2' then raise exception 'permission_denied'; end if;
  if char_length(trim(p_reason)) < 5 then raise exception 'invalid_reason'; end if;
  select m.* into actor from public.beta_memberships m
  join public.beta_user_context c on c.organization_id = m.organization_id and c.user_id = m.user_id
  where m.user_id = auth.uid() and m.status = 'active' and m.role in ('owner', 'admin') for update of m;
  if not found then raise exception 'permission_denied'; end if;
  select * into current_owner from public.beta_memberships
  where organization_id = actor.organization_id and status = 'active' and role = 'owner' for update;
  if not found then raise exception 'owner_invariant'; end if;
  select * into successor from public.beta_memberships
  where id = p_membership_id and organization_id = actor.organization_id and status = 'active'
  for update;
  if not found or successor.id = current_owner.id then raise exception 'invalid_successor'; end if;

  update public.beta_memberships set role = 'admin', updated_at = now() where id = current_owner.id;
  update public.beta_memberships set role = 'owner', updated_at = now() where id = successor.id;
  update public.beta_organizations set owner_user_id = successor.user_id where id = actor.organization_id;
  insert into public.beta_admin_audit (organization_id, actor_user_id, action, target_id, reason, details)
  values (actor.organization_id, auth.uid(), 'organization.owner_transferred', successor.id, trim(p_reason),
    jsonb_build_object('previous_owner_membership_id', current_owner.id, 'successor_membership_id', successor.id));
end $$;

create or replace function public.beta_feature_flags_snapshot()
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare
  caller uuid := auth.uid();
  active_organization uuid;
  can_manage boolean := false;
begin
  if caller is null then raise exception 'authentication_required'; end if;
  select c.organization_id into active_organization
  from public.beta_user_context c
  join public.beta_memberships m on m.organization_id = c.organization_id and m.user_id = c.user_id
  where c.user_id = caller and m.status = 'active';
  if active_organization is null then raise exception 'membership_required'; end if;
  can_manage := lower(coalesce(auth.jwt() ->> 'email', '')) = 'flanhenriquee@icloud.com'
    and coalesce(auth.jwt() ->> 'aal', 'aal1') = 'aal2'
    and exists (
      select 1 from public.beta_memberships m
      where m.organization_id = active_organization and m.user_id = caller
        and m.status = 'active' and m.role in ('owner', 'admin')
    );
  return jsonb_build_object(
    'can_manage', can_manage,
    'refreshed_at', now(),
    'flags', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'key', f.key,
        'description', f.description,
        'enabled', f.enabled,
        'rollout_percentage', f.rollout_percentage,
        'kill_switch', f.kill_switch,
        'effective', case
          when f.kill_switch or not f.enabled then false
          when caller = any(f.user_ids) or active_organization = any(f.tenant_ids) then true
          else mod((('x' || substr(md5(f.key || ':' || caller::text), 1, 8))::bit(32)::bigint), 10000) < f.rollout_percentage * 100
        end,
        'reason', case
          when f.kill_switch then 'kill-switch'
          when not f.enabled then 'disabled'
          when caller = any(f.user_ids) then 'user-target'
          when active_organization = any(f.tenant_ids) then 'tenant-target'
          else 'rollout'
        end,
        'updated_at', f.updated_at
      ) order by f.key), '[]'::jsonb)
      from public.beta_feature_flags f
    )
  );
end $$;

create or replace function public.beta_admin_update_feature_flag(
  p_key text,
  p_enabled boolean,
  p_rollout_percentage integer,
  p_kill_switch boolean,
  p_reason text
)
returns void language plpgsql security definer set search_path = '' as $$
declare actor public.beta_memberships; previous public.beta_feature_flags;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'flanhenriquee@icloud.com'
     or coalesce(auth.jwt() ->> 'aal', 'aal1') <> 'aal2' then raise exception 'permission_denied'; end if;
  if p_rollout_percentage not between 0 and 100 then raise exception 'invalid_rollout'; end if;
  if char_length(trim(p_reason)) < 5 then raise exception 'invalid_reason'; end if;
  select m.* into actor from public.beta_memberships m
  join public.beta_user_context c on c.organization_id = m.organization_id and c.user_id = m.user_id
  where m.user_id = auth.uid() and m.status = 'active' and m.role in ('owner', 'admin');
  if not found then raise exception 'permission_denied'; end if;
  select * into previous from public.beta_feature_flags where key = p_key for update;
  if not found then raise exception 'invalid_flag'; end if;
  update public.beta_feature_flags set
    enabled = p_enabled,
    rollout_percentage = p_rollout_percentage,
    kill_switch = p_kill_switch,
    updated_by = auth.uid(),
    updated_at = now()
  where key = p_key;
  insert into public.beta_admin_audit (organization_id, actor_user_id, action, reason, details)
  values (actor.organization_id, auth.uid(), 'feature_flag.updated', trim(p_reason), jsonb_build_object(
    'key', p_key,
    'before', jsonb_build_object('enabled', previous.enabled, 'rollout_percentage', previous.rollout_percentage, 'kill_switch', previous.kill_switch),
    'after', jsonb_build_object('enabled', p_enabled, 'rollout_percentage', p_rollout_percentage, 'kill_switch', p_kill_switch)
  ));
end $$;

create or replace function public.beta_admin_operational_snapshot()
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare actor public.beta_memberships;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'flanhenriquee@icloud.com'
     or coalesce(auth.jwt() ->> 'aal', 'aal1') <> 'aal2' then raise exception 'permission_denied'; end if;
  select m.* into actor from public.beta_memberships m
  join public.beta_user_context c on c.organization_id = m.organization_id and c.user_id = m.user_id
  where m.user_id = auth.uid() and m.status = 'active' and m.role in ('owner', 'admin');
  if not found then raise exception 'permission_denied'; end if;
  return (
    with scoped as (
      select event_type, severity, component, duration_ms, trace_id, span_id, parent_span_id, created_at
      from public.beta_operational_events
      where created_at >= now() - interval '24 hours'
    ), totals as (
      select count(*)::integer as events,
        count(*) filter (where severity = 'error')::integer as errors,
        count(*) filter (where severity = 'warning')::integer as warnings,
        round(coalesce(percentile_cont(0.50) within group (order by duration_ms) filter (where duration_ms is not null), 0))::integer as latency_p50_ms,
        round(coalesce(percentile_cont(0.95) within group (order by duration_ms) filter (where duration_ms is not null), 0))::integer as latency_p95_ms,
        max(created_at) as last_event_at
      from scoped
    )
    select jsonb_build_object(
      'window_hours', 24,
      'generated_at', now(),
      'events', totals.events,
      'errors', totals.errors,
      'warnings', totals.warnings,
      'error_rate', case when totals.events = 0 then 0 else round((totals.errors::numeric / totals.events) * 100, 2) end,
      'latency_p50_ms', totals.latency_p50_ms,
      'latency_p95_ms', totals.latency_p95_ms,
      'last_event_at', totals.last_event_at,
      'alerts', (
        select coalesce(jsonb_agg(jsonb_build_object(
          'id', id,
          'rule_key', rule_key,
          'severity', severity,
          'component', component,
          'status', status,
          'fired_at', fired_at,
          'acknowledged_at', acknowledged_at
        ) order by (status = 'firing') desc, fired_at desc), '[]'::jsonb)
        from (select * from public.beta_operational_alerts where fired_at >= now() - interval '24 hours' order by fired_at desc limit 20) alert_rows
      ),
      'recent_spans', (
        select coalesce(jsonb_agg(jsonb_build_object(
          'trace_id', trace_id,
          'span_id', span_id,
          'parent_span_id', parent_span_id,
          'operation', event_type,
          'component', component,
          'severity', severity,
          'duration_ms', duration_ms,
          'created_at', created_at
        ) order by created_at desc), '[]'::jsonb)
        from (select * from scoped where trace_id is not null and span_id is not null order by created_at desc limit 20) spans
      ),
      'components', (
        select coalesce(jsonb_agg(jsonb_build_object('component', component, 'events', events, 'errors', errors) order by errors desc, events desc, component), '[]'::jsonb)
        from (
          select component, count(*)::integer as events, count(*) filter (where severity = 'error')::integer as errors
          from scoped group by component
        ) grouped
      )
    ) from totals
  );
end $$;

create or replace function public.beta_admin_acknowledge_operational_alert(p_alert_id bigint, p_reason text)
returns void language plpgsql security definer set search_path = '' as $$
declare actor public.beta_memberships;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'flanhenriquee@icloud.com'
     or coalesce(auth.jwt() ->> 'aal', 'aal1') <> 'aal2' then raise exception 'permission_denied'; end if;
  select m.* into actor from public.beta_memberships m
  join public.beta_user_context c on c.organization_id = m.organization_id and c.user_id = m.user_id
  where m.user_id = auth.uid() and m.status = 'active' and m.role in ('owner', 'admin');
  if not found then raise exception 'permission_denied'; end if;
  if char_length(trim(coalesce(p_reason, ''))) < 10 or char_length(trim(p_reason)) > 500 then
    raise exception 'invalid_reason';
  end if;
  update public.beta_operational_alerts set
    status = 'acknowledged', acknowledged_at = clock_timestamp(),
    acknowledged_by = auth.uid(), acknowledgement_reason = trim(p_reason)
  where id = p_alert_id and status = 'firing';
  if not found then raise exception 'invalid_alert'; end if;
  insert into public.beta_admin_audit (organization_id, actor_user_id, action, reason, details)
  values (actor.organization_id, auth.uid(), 'operational_alert.acknowledged', trim(p_reason), jsonb_build_object('alert_id', p_alert_id));
end $$;

create or replace function public.beta_admin_health_snapshot()
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare actor public.beta_memberships;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'flanhenriquee@icloud.com'
     or coalesce(auth.jwt() ->> 'aal', 'aal1') <> 'aal2' then raise exception 'permission_denied'; end if;
  select m.* into actor from public.beta_memberships m
  join public.beta_user_context c on c.organization_id = m.organization_id and c.user_id = m.user_id
  where m.user_id = auth.uid() and m.status = 'active' and m.role in ('owner', 'admin');
  if not found then raise exception 'permission_denied'; end if;
  perform 1 from public.beta_operational_events limit 1;
  return jsonb_build_object('status', 'healthy', 'auth', true, 'database', true, 'rbac', true, 'checked_at', clock_timestamp());
end $$;

create or replace function public.beta_service_readiness()
returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  perform 1 from public.beta_operational_events limit 1;
  return jsonb_build_object('status', 'healthy', 'database', true, 'checked_at', clock_timestamp());
end $$;

create or replace function public.beta_admin_prometheus_metrics()
returns text language plpgsql stable security definer set search_path = '' as $$
declare snapshot jsonb := public.beta_admin_operational_snapshot();
begin
  return
    '# HELP volt_beta_operational_events_24h Operational events recorded in the last 24 hours.' || E'\n' ||
    '# TYPE volt_beta_operational_events_24h gauge' || E'\n' ||
    'volt_beta_operational_events_24h ' || (snapshot ->> 'events') || E'\n' ||
    '# HELP volt_beta_operational_errors_24h Error events recorded in the last 24 hours.' || E'\n' ||
    '# TYPE volt_beta_operational_errors_24h gauge' || E'\n' ||
    'volt_beta_operational_errors_24h ' || (snapshot ->> 'errors') || E'\n' ||
    '# HELP volt_beta_operational_warnings_24h Warning events recorded in the last 24 hours.' || E'\n' ||
    '# TYPE volt_beta_operational_warnings_24h gauge' || E'\n' ||
    'volt_beta_operational_warnings_24h ' || (snapshot ->> 'warnings') || E'\n' ||
    '# HELP volt_beta_operational_error_ratio_24h Error ratio from zero to one in the last 24 hours.' || E'\n' ||
    '# TYPE volt_beta_operational_error_ratio_24h gauge' || E'\n' ||
    'volt_beta_operational_error_ratio_24h ' || round(((snapshot ->> 'error_rate')::numeric / 100), 6) || E'\n' ||
    '# HELP volt_beta_operation_duration_p50_ms Median measured operation duration in milliseconds.' || E'\n' ||
    '# TYPE volt_beta_operation_duration_p50_ms gauge' || E'\n' ||
    'volt_beta_operation_duration_p50_ms ' || (snapshot ->> 'latency_p50_ms') || E'\n' ||
    '# HELP volt_beta_operation_duration_p95_ms 95th percentile measured operation duration in milliseconds.' || E'\n' ||
    '# TYPE volt_beta_operation_duration_p95_ms gauge' || E'\n' ||
    'volt_beta_operation_duration_p95_ms ' || (snapshot ->> 'latency_p95_ms') || E'\n';
end $$;

revoke all on function public.beta_admin_bootstrap(text, text), public.beta_admin_snapshot(), public.beta_user_permissions(), public.beta_admin_invite_member(text, text), public.beta_invitation_preview(text), public.beta_accept_invitation(text, text), public.beta_decline_invitation(text), public.beta_admin_update_member(uuid, text, text, text), public.beta_admin_transfer_owner(uuid, text), public.beta_feature_flags_snapshot(), public.beta_admin_update_feature_flag(text, boolean, integer, boolean, text), public.beta_admin_operational_snapshot(), public.beta_admin_acknowledge_operational_alert(bigint, text), public.beta_admin_health_snapshot(), public.beta_admin_prometheus_metrics() from public, anon;
grant execute on function public.beta_admin_bootstrap(text, text), public.beta_admin_snapshot(), public.beta_user_permissions(), public.beta_admin_invite_member(text, text), public.beta_invitation_preview(text), public.beta_accept_invitation(text, text), public.beta_decline_invitation(text), public.beta_admin_update_member(uuid, text, text, text), public.beta_admin_transfer_owner(uuid, text), public.beta_feature_flags_snapshot(), public.beta_admin_update_feature_flag(text, boolean, integer, boolean, text), public.beta_admin_operational_snapshot(), public.beta_admin_acknowledge_operational_alert(bigint, text), public.beta_admin_health_snapshot(), public.beta_admin_prometheus_metrics() to authenticated;
revoke all on function public.beta_raise_operational_alert() from public, anon, authenticated;
revoke all on function public.beta_service_readiness() from public, anon, authenticated;
grant execute on function public.beta_service_readiness() to service_role;
