import { findSouthTariffRule, listSouthTariffRulesForState } from "./south-tariff-catalog.js";
import { MERCOSUR_COUNTRIES, getCountry, normalizeRegionalContext, formatMoney } from "./mercosur-region.js";
import { listUruguayProviders, listUruguayTariffRules } from "./uruguay-tariff-catalog.js";

const STORAGE_KEY="volt:beta:locality-context-v1";
const BRAZIL_STATES=[["AC","Acre"],["AL","Alagoas"],["AP","Amapá"],["AM","Amazonas"],["BA","Bahia"],["CE","Ceará"],["DF","Distrito Federal"],["ES","Espírito Santo"],["GO","Goiás"],["MA","Maranhão"],["MT","Mato Grosso"],["MS","Mato Grosso do Sul"],["MG","Minas Gerais"],["PA","Pará"],["PB","Paraíba"],["PR","Paraná"],["PE","Pernambuco"],["PI","Piauí"],["RJ","Rio de Janeiro"],["RN","Rio Grande do Norte"],["RS","Rio Grande do Sul"],["RO","Rondônia"],["RR","Roraima"],["SC","Santa Catarina"],["SP","São Paulo"],["SE","Sergipe"],["TO","Tocantins"]];
const URUGUAY_DEPARTMENTS=[["AR","Artigas"],["CA","Canelones"],["CL","Cerro Largo"],["CO","Colonia"],["DU","Durazno"],["FS","Flores"],["FD","Florida"],["LA","Lavalleja"],["MA","Maldonado"],["MO","Montevideo"],["PA","Paysandú"],["RN","Río Negro"],["RV","Rivera"],["RO","Rocha"],["SA","Salto"],["SJ","San José"],["SO","Soriano"],["TA","Tacuarembó"],["TT","Treinta y Tres"]];
queueMicrotask(initializeLocalityContext);

function initializeLocalityContext(){
 const settingsPage=document.querySelector("#beta-settings"); if(!settingsPage||document.querySelector("#beta-locality-form"))return;
 const section=document.createElement("section"); section.className="settings-group"; section.setAttribute("aria-labelledby","beta-locality-title");
 section.innerHTML=`<div class="settings-row"><div><h3 id="beta-locality-title">Região e concessionárias</h3><small>Base regional para regras de energia e água.</small></div></div>
 <form id="beta-locality-form" class="form compact-form">
 <label><span>País</span><select id="beta-locality-country" required>${MERCOSUR_COUNTRIES.map(i=>`<option value="${i.code}" ${i.enabled?"":"disabled"}>${i.name}${i.pilot?" — piloto":i.enabled?"":" — em preparação"}</option>`).join("")}</select></label>
 <label><span id="beta-subdivision-label">UF</span><select id="beta-locality-state" required></select></label>
 <label><span id="beta-city-label">Município</span><input id="beta-locality-city" type="text" maxlength="80" autocomplete="address-level2" required></label>
 <label><span>Concessionária de energia</span><input id="beta-locality-energy-provider" type="text" maxlength="120" list="beta-energy-provider-options"></label>
 <label><span>Concessionária de água</span><input id="beta-locality-water-provider" type="text" maxlength="120" list="beta-water-provider-options"></label>
 <datalist id="beta-energy-provider-options"></datalist><datalist id="beta-water-provider-options"></datalist>
 <div id="beta-uruguay-energy-options" class="full-row" hidden><div class="form compact-form"><label><span>Tarifa UTE</span><select id="beta-uy-energy-plan"></select></label><label><span>Potência contratada (kW)</span><input id="beta-uy-contracted-power" type="number" min="0.1" step="0.1" inputmode="decimal"></label><p class="note full-row">No piloto uruguaio, o Volt calcula automaticamente apenas a Tarifa Residencial Simple.</p></div></div>
 <div id="beta-uruguay-water-options" class="full-row" hidden><div class="form compact-form"><label><span>Zona OSE</span><select id="beta-uy-ose-zone"><option value="">Seleccionar</option><option value="general">General</option><option value="balnearia">Balnearia</option><option value="maldonado">Maldonado</option></select></label><label><span>Diámetro de conexión (mm)</span><select id="beta-uy-ose-diameter"><option value="">Seleccionar</option><option value="13">13 mm</option><option value="19">19 mm</option><option value="25">25 mm</option></select></label><label><span>Promedio anual (m³/mes)</span><input id="beta-uy-ose-average" type="number" min="0" step="0.1" inputmode="decimal" placeholder="Opcional"></label><label class="checkbox-row"><input id="beta-uy-ose-sanitation" type="checkbox"><span>La cuenta incluye saneamiento</span></label><p class="note full-row">El saneamiento se registra según la factura; Volt no lo infiere solo por la localidad.</p></div></div>
 <button class="secondary-button" type="submit">Salvar região</button><p id="beta-locality-status" class="note status-message full-row" role="status" aria-live="polite"></p></form><div id="beta-regional-tariff-rules" class="full-row" aria-live="polite"></div>`;
 const cycleSection=settingsPage.querySelector("#beta-cycle-form")?.closest("section.settings-group"); if(cycleSection)cycleSection.before(section); else settingsPage.append(section);
 const q=s=>section.querySelector(s),form=q("#beta-locality-form"),country=q("#beta-locality-country"),state=q("#beta-locality-state"),city=q("#beta-locality-city"),energyProvider=q("#beta-locality-energy-provider"),waterProvider=q("#beta-locality-water-provider"),energyPlan=q("#beta-uy-energy-plan"),contractedPower=q("#beta-uy-contracted-power"),oseZone=q("#beta-uy-ose-zone"),oseDiameter=q("#beta-uy-ose-diameter"),oseAverage=q("#beta-uy-ose-average"),oseSanitation=q("#beta-uy-ose-sanitation"),status=q("#beta-locality-status");
 const saved=readLocality(); country.value=saved.country||"BR"; updateCountryUi(country.value,section,saved.state); state.value=saved.state||""; city.value=saved.city||""; energyProvider.value=saved.energyProvider||defaultEnergyProvider(country.value); waterProvider.value=saved.waterProvider||defaultWaterProvider(country.value); energyPlan.value=saved.energyPlan||"uy-ute-trs-2026"; contractedPower.value=saved.contractedPowerKw||""; oseZone.value=saved.oseZone||""; oseDiameter.value=saved.oseConnectionDiameterMm||""; oseAverage.value=saved.oseAnnualAverageM3??""; oseSanitation.checked=Boolean(saved.oseSanitation); updateProviderOptions(country.value,state.value,section); updateStatus(saved,status); publish(saved); renderRegionalRules(saved,section);
 const render=()=>renderRegionalRules(currentFormContext(),section);
 country.addEventListener("change",()=>{updateCountryUi(country.value,section,"");energyProvider.value=defaultEnergyProvider(country.value);waterProvider.value=defaultWaterProvider(country.value);energyPlan.value=country.value==="UY"?"uy-ute-trs-2026":"";contractedPower.value="";oseZone.value="";oseDiameter.value="";oseAverage.value="";oseSanitation.checked=false;updateProviderOptions(country.value,state.value,section);render();});
 state.addEventListener("change",()=>{if(country.value==="UY"&&state.value==="MA"&&!oseZone.value)oseZone.value="maldonado";updateProviderOptions(country.value,state.value,section);render();});
 [energyProvider,waterProvider,energyPlan,contractedPower,oseZone,oseDiameter,oseAverage,oseSanitation].forEach(el=>{el.addEventListener("input",render);el.addEventListener("change",render);});
 form.addEventListener("submit",event=>{event.preventDefault();const selected=getCountry(country.value),next=currentFormContext();if(!selected.enabled){status.textContent=`${selected.name} ainda está em preparação.`;return;}if(!next.state||!next.city){status.textContent=`Informe ${selected.subdivisionLabel} e ${selected.cityLabel.toLowerCase()} para definir a jurisdição.`;return;}if(next.country==="UY"&&next.energyPlan==="uy-ute-trs-2026"&&!next.contractedPowerKw){status.textContent="Informe la potencia contratada de UTE.";contractedPower.focus();return;}if(next.country==="UY"&&(!next.oseZone||!next.oseConnectionDiameterMm)){status.textContent="Para calcular OSE, seleccione la zona tarifaria y el diámetro de conexión.";(!next.oseZone?oseZone:oseDiameter).focus();return;}localStorage.setItem(STORAGE_KEY,JSON.stringify(next));updateStatus(next,status);publish(next);renderRegionalRules(next,section);window.dispatchEvent(new CustomEvent("volt:locality-context",{detail:structuredClone(next)}));});
 function currentFormContext(){return normalizeRegionalContext({country:country.value,state:state.value,city:city.value,energyProvider:energyProvider.value,waterProvider:waterProvider.value,energyPlan:country.value==="UY"?energyPlan.value:"",contractedPowerKw:country.value==="UY"?contractedPower.value:null,oseZone:country.value==="UY"?oseZone.value:"",oseConnectionDiameterMm:country.value==="UY"?oseDiameter.value:null,oseAnnualAverageM3:country.value==="UY"?oseAverage.value:null,oseSanitation:country.value==="UY"?oseSanitation.checked:false,updatedAt:new Date().toISOString()});}
}
function updateCountryUi(code,section,selectedState=""){const c=getCountry(code),state=section.querySelector("#beta-locality-state"),opts=c.code==="UY"?URUGUAY_DEPARTMENTS:BRAZIL_STATES;section.querySelector("#beta-subdivision-label").textContent=c.subdivisionLabel;section.querySelector("#beta-city-label").textContent=c.cityLabel;state.replaceChildren(makeOption("",c.code==="UY"?"Seleccionar":"Selecione"),...opts.map(([v,n])=>makeOption(v,`${v} — ${n}`)));if(selectedState&&opts.some(([v])=>v===selectedState))state.value=selectedState;section.querySelector("#beta-locality-city").placeholder=c.code==="UY"?"Ex.: Montevideo":"Ex.: Porto Alegre";section.querySelector("#beta-uruguay-energy-options").hidden=c.code!=="UY";section.querySelector("#beta-uruguay-water-options").hidden=c.code!=="UY";section.querySelector("#beta-uy-energy-plan").replaceChildren(...listUruguayTariffRules("energy").map(r=>makeOption(r.id,r.customerClass)));}
function updateProviderOptions(code,state,section){const e=section.querySelector("#beta-energy-provider-options"),w=section.querySelector("#beta-water-provider-options");if(code==="UY"){e.replaceChildren(...listUruguayProviders("energy").map(v=>makeOption(v,v)));w.replaceChildren(...listUruguayProviders("water").map(v=>makeOption(v,v)));return;}const rules=listSouthTariffRulesForState(state);e.replaceChildren(...uniqueOptions(rules.filter(r=>r.utility==="energy").map(r=>r.provider)));w.replaceChildren(...uniqueOptions(rules.filter(r=>r.utility==="water").map(r=>r.provider)));}
function renderRegionalRules(context,section){const container=section.querySelector("#beta-regional-tariff-rules");if(!container)return;container.replaceChildren();if(context.country==="UY"){const plan=listUruguayTariffRules("energy").find(r=>r.id===context.energyPlan)||listUruguayTariffRules("energy")[0],water=listUruguayTariffRules("water")[0];if(plan)container.append(buildUruguayRuleCard(plan,context));if(water)container.append(buildUruguayRuleCard(water,context));return;}if(context.country!=="BR"||!context.state||!["PR","SC","RS"].includes(String(context.state).toUpperCase()))return;for(const rule of [findSouthTariffRule({state:context.state,utility:"energy",provider:context.energyProvider}),findSouthTariffRule({state:context.state,utility:"water",provider:context.waterProvider})].filter(Boolean))container.append(buildRuleCard(rule,context));}
function buildUruguayRuleCard(rule,context){const card=document.createElement("article"),title=document.createElement("h3"),details=document.createElement("p"),source=document.createElement("p");card.className="card tariff-info-card regional-tariff-card";title.textContent=`${rule.utility==="energy"?"Energía":"Agua"} · ${rule.provider}`;details.className=source.className="note";if(rule.id==="uy-ute-trs-2026"){const tiers=rule.energyTiers.map(t=>`${t.minKwh}${t.maxKwh?`–${t.maxKwh}`:"+"} kWh: ${formatMoney(t.ratePerKwh,context)}/kWh`).join(" · ");details.textContent=`${rule.customerClass}. ${tiers}. Cargo fijo ${formatMoney(rule.fixedMonthlyCharge,context)} + potencia ${formatMoney(rule.contractedPowerRatePerKw,context)}/kW. Valores sin IVA.`;}else if(rule.utility==="water")details.textContent=context.oseZone&&context.oseConnectionDiameterMm?`OSE preparada: zona ${context.oseZone}, conexión ${context.oseConnectionDiameterMm} mm${context.oseSanitation?", con saneamiento declarado":""}.`:"Seleccione zona OSE y diámetro de conexión para habilitar el cálculo.";else details.textContent=rule.note||"Regla oficial identificada.";source.textContent=`Fuente: ${rule.source}.`;card.append(title,details,source);return card;}
function buildRuleCard(rule,context){const card=document.createElement("article"),title=document.createElement("h3"),details=document.createElement("p"),source=document.createElement("p");card.className="card tariff-info-card regional-tariff-card";title.textContent=`${rule.utility==="energy"?"Energia":"Água"} · ${rule.provider}`;details.className=source.className="note";details.textContent=rule.utility==="energy"&&Number.isFinite(rule.ratePerKwh)?`${rule.customerClass}: ${formatMoney(rule.ratePerKwh,context)}/kWh. Não inclui ${(rule.excludes||[]).join(", ")}.`:`${rule.customerClass}. ${rule.note||""}`;source.textContent=`Fonte: ${rule.source} · vigência a partir de ${formatDate(rule.validFrom,context.locale)}.`;card.append(title,details,source);return card;}
function readLocality(){try{return normalizeRegionalContext(JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}"));}catch{return normalizeRegionalContext({});}}
function updateStatus(context,status){if(!context.state||!context.city){status.textContent="Região ainda não configurada. Regras automáticas permanecem desativadas.";return;}const c=getCountry(context.country);status.textContent=`${c.name}${c.pilot?" · piloto Beta":""} · ${context.city} · ${context.state}. Jurisdição: ${context.jurisdiction}. Moeda: ${context.currency}.`;}
function publish(context){const n=normalizeRegionalContext(context),energyRule=n.country==="BR"?findSouthTariffRule({state:n.state,utility:"energy",provider:n.energyProvider}):null,waterRule=n.country==="BR"?findSouthTariffRule({state:n.state,utility:"water",provider:n.waterProvider}):null;window.VOLT_LOCALITY_CONTEXT=Object.freeze({...n,automaticRules:Boolean(energyRule?.automatic||waterRule?.automatic||n.country==="UY"),energyRuleId:n.country==="UY"?n.energyPlan||null:energyRule?.id||null,waterRuleId:n.country==="UY"?"uy-ose-residencial-2026":waterRule?.id||null});window.VOLT_REGION_CONTEXT=Object.freeze({...n});}
function defaultEnergyProvider(c){return c==="UY"?"UTE":"";}function defaultWaterProvider(c){return c==="UY"?"OSE":"";}function makeOption(v,l){const o=document.createElement("option");o.value=v;o.textContent=l;return o;}function uniqueOptions(values){return[...new Set(values)].map(v=>makeOption(v,v));}function formatDate(value,locale="pt-BR"){const d=new Date(`${value}T12:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString(locale);}
