create schema if not exists volt_private;
revoke all on schema volt_private from public;
grant usage on schema volt_private to authenticated;

create or replace function volt_private.has_org_access(p_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.beta_memberships m
    where m.organization_id = p_organization_id
      and m.user_id = auth.uid()
      and m.status = 'active'
  );
$$;

create or replace function volt_private.can_write_org(p_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.beta_memberships m
    where m.organization_id = p_organization_id
      and m.user_id = auth.uid()
      and m.status = 'active'
      and m.role in ('owner', 'admin', 'member')
  );
$$;

create or replace function volt_private.is_org_admin(p_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.beta_memberships m
    where m.organization_id = p_organization_id
      and m.user_id = auth.uid()
      and m.status = 'active'
      and m.role in ('owner', 'admin')
  );
$$;

revoke all on function volt_private.has_org_access(uuid) from public, anon, authenticated;
revoke all on function volt_private.can_write_org(uuid) from public, anon, authenticated;
revoke all on function volt_private.is_org_admin(uuid) from public, anon, authenticated;
grant execute on function volt_private.has_org_access(uuid) to authenticated;
grant execute on function volt_private.can_write_org(uuid) to authenticated;
grant execute on function volt_private.is_org_admin(uuid) to authenticated;

create table public.consumer_units (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.beta_organizations(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete restrict,
  service text not null check (service in ('energy', 'water')),
  measurement_unit text not null check (measurement_unit in ('kWh', 'm3')),
  label text not null,
  country text not null default 'BR' check (country ~ '^[A-Z]{2}$'),
  state text check (state is null or state ~ '^[A-Z]{2}$'),
  city text,
  distributor text,
  class text,
  subclass text,
  system_type text not null default 'not_identified' check (system_type in ('sin', 'isolated', 'not_identified')),
  provider_account_ref text,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint consumer_units_service_measurement_check check (
    (service = 'energy' and measurement_unit = 'kWh') or
    (service = 'water' and measurement_unit = 'm3')
  ),
  unique (id, organization_id)
);

create table public.billing_cycles (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  consumer_unit_id uuid not null,
  cycle_start date not null,
  cycle_end date not null,
  status text not null default 'open' check (status in ('open', 'closed', 'awaiting_bill', 'billed', 'reconciled')),
  target_consumption numeric check (target_consumption is null or target_consumption >= 0),
  target_cost numeric check (target_cost is null or target_cost >= 0),
  source_type text check (source_type is null or source_type in ('volt_measured', 'user_informed', 'bill_identified', 'volt_calculated', 'rule_predicted')),
  confidence text not null default 'not_identified' check (confidence in ('confirmed', 'probable', 'not_identified')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_cycles_dates_check check (cycle_end >= cycle_start),
  constraint billing_cycles_unit_org_fk foreign key (consumer_unit_id, organization_id)
    references public.consumer_units(id, organization_id) on delete cascade,
  unique (consumer_unit_id, cycle_start, cycle_end),
  unique (id, organization_id)
);

create table public.unit_meter_readings (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  consumer_unit_id uuid not null,
  billing_cycle_id uuid,
  value numeric not null check (value >= 0),
  measured_at timestamptz not null,
  source_type text not null check (source_type in ('volt_measured', 'user_informed', 'bill_identified', 'volt_calculated', 'rule_predicted')),
  confidence text not null default 'confirmed' check (confidence in ('confirmed', 'probable', 'not_identified')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint unit_meter_readings_unit_org_fk foreign key (consumer_unit_id, organization_id)
    references public.consumer_units(id, organization_id) on delete cascade,
  constraint unit_meter_readings_cycle_org_fk foreign key (billing_cycle_id, organization_id)
    references public.billing_cycles(id, organization_id) on delete set null,
  unique (consumer_unit_id, value, measured_at)
);

create table public.regulatory_rules (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  name text not null,
  service text not null check (service in ('energy', 'water', 'both')),
  jurisdiction text not null check (jurisdiction in ('federal', 'state', 'municipal', 'distributor')),
  country text not null default 'BR' check (country ~ '^[A-Z]{2}$'),
  state text check (state is null or state ~ '^[A-Z]{2}$'),
  city text,
  distributor text,
  valid_from date not null,
  valid_until date,
  legal_basis text,
  source_title text,
  source_url text,
  conditions jsonb not null default '{}'::jsonb,
  effect jsonb not null default '{}'::jsonb,
  priority integer not null default 100,
  status text not null default 'draft' check (status in ('draft', 'published', 'superseded', 'retired')),
  version integer not null check (version > 0),
  supersedes_rule_id uuid references public.regulatory_rules(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint regulatory_rules_validity_check check (valid_until is null or valid_until >= valid_from),
  unique (code, version)
);

create table public.bills (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  consumer_unit_id uuid not null,
  billing_cycle_id uuid not null,
  revision integer not null default 1 check (revision > 0),
  supersedes_bill_id uuid,
  issued_at date,
  due_date date,
  billing_method text not null default 'not_identified' check (billing_method in ('metered', 'average', 'estimated', 'adjusted', 'not_identified')),
  measured_consumption numeric check (measured_consumption is null or measured_consumption >= 0),
  billed_consumption numeric check (billed_consumption is null or billed_consumption >= 0),
  estimated_total numeric check (estimated_total is null or estimated_total >= 0),
  invoice_total numeric check (invoice_total is null or invoice_total >= 0),
  currency text not null default 'BRL' check (currency ~ '^[A-Z]{3}$'),
  source_type text check (source_type is null or source_type in ('volt_measured', 'user_informed', 'bill_identified', 'volt_calculated', 'rule_predicted')),
  confidence text not null default 'not_identified' check (confidence in ('confirmed', 'probable', 'not_identified')),
  status text not null default 'received' check (status in ('received', 'validated', 'reconciled', 'revised')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bills_unit_org_fk foreign key (consumer_unit_id, organization_id)
    references public.consumer_units(id, organization_id) on delete cascade,
  constraint bills_cycle_org_fk foreign key (billing_cycle_id, organization_id)
    references public.billing_cycles(id, organization_id) on delete cascade,
  unique (billing_cycle_id, revision),
  unique (id, organization_id),
  constraint bills_supersedes_org_fk foreign key (supersedes_bill_id, organization_id)
    references public.bills(id, organization_id) on delete restrict
);

create table public.bill_components (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  bill_id uuid not null,
  position integer not null default 0 check (position >= 0),
  category text not null,
  code text not null,
  label text not null,
  direction text not null check (direction in ('charge', 'credit', 'neutral')),
  quantity numeric,
  quantity_unit text,
  unit_rate numeric,
  percentage numeric,
  amount numeric check (amount is null or amount >= 0),
  source_type text check (source_type is null or source_type in ('volt_measured', 'user_informed', 'bill_identified', 'volt_calculated', 'rule_predicted')),
  confidence text not null default 'not_identified' check (confidence in ('confirmed', 'probable', 'not_identified')),
  evidence_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bill_components_bill_org_fk foreign key (bill_id, organization_id)
    references public.bills(id, organization_id) on delete cascade,
  unique (id, organization_id)
);

create table public.reconciliations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  bill_id uuid not null,
  calculated_total numeric not null check (calculated_total >= 0),
  invoice_total numeric not null check (invoice_total >= 0),
  difference_amount numeric not null,
  difference_percent numeric,
  measured_minus_billed numeric,
  classification text not null check (classification in ('matching', 'small_difference', 'relevant_difference')),
  status text not null default 'pending' check (status in ('pending', 'reconciled', 'partially_reconciled', 'not_reconciled')),
  engine_version text not null,
  diagnostics jsonb not null default '{}'::jsonb,
  source_type text not null default 'volt_calculated' check (source_type = 'volt_calculated'),
  confidence text not null default 'probable' check (confidence in ('confirmed', 'probable', 'not_identified')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reconciliations_bill_org_fk foreign key (bill_id, organization_id)
    references public.bills(id, organization_id) on delete cascade,
  unique (bill_id),
  unique (id, organization_id)
);

create table public.regulatory_profiles (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  consumer_unit_id uuid not null,
  rule_code text not null,
  regulatory_rule_id uuid references public.regulatory_rules(id) on delete restrict,
  state text not null check (state in ('not_analyzed', 'possible', 'apparent_eligible', 'confirmed_on_bill', 'not_identified')),
  source_type text check (source_type is null or source_type in ('volt_measured', 'user_informed', 'bill_identified', 'volt_calculated', 'rule_predicted')),
  confidence text not null default 'not_identified' check (confidence in ('confirmed', 'probable', 'not_identified')),
  evidence_bill_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint regulatory_profiles_unit_org_fk foreign key (consumer_unit_id, organization_id)
    references public.consumer_units(id, organization_id) on delete cascade,
  constraint regulatory_profiles_bill_org_fk foreign key (evidence_bill_id, organization_id)
    references public.bills(id, organization_id) on delete restrict
);

create table public.rule_applications (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  regulatory_rule_id uuid not null references public.regulatory_rules(id) on delete restrict,
  consumer_unit_id uuid not null,
  billing_cycle_id uuid,
  bill_id uuid,
  bill_component_id uuid,
  engine_stage text not null check (engine_stage in ('legal', 'billing', 'reconciliation')),
  outcome text not null check (outcome in ('applied', 'not_applied', 'possible', 'confirmed', 'not_identified')),
  effect_amount numeric,
  source_type text check (source_type is null or source_type in ('volt_measured', 'user_informed', 'bill_identified', 'volt_calculated', 'rule_predicted')),
  confidence text not null default 'not_identified' check (confidence in ('confirmed', 'probable', 'not_identified')),
  explanation text,
  created_at timestamptz not null default now(),
  constraint rule_applications_unit_org_fk foreign key (consumer_unit_id, organization_id)
    references public.consumer_units(id, organization_id) on delete cascade,
  constraint rule_applications_cycle_org_fk foreign key (billing_cycle_id, organization_id)
    references public.billing_cycles(id, organization_id) on delete cascade,
  constraint rule_applications_bill_org_fk foreign key (bill_id, organization_id)
    references public.bills(id, organization_id) on delete cascade,
  constraint rule_applications_component_org_fk foreign key (bill_component_id, organization_id)
    references public.bill_components(id, organization_id) on delete cascade
);

create index consumer_units_org_service_idx on public.consumer_units (organization_id, service, status);
create index billing_cycles_unit_start_idx on public.billing_cycles (consumer_unit_id, cycle_start desc);
create index unit_meter_readings_unit_measured_idx on public.unit_meter_readings (consumer_unit_id, measured_at desc);
create index bills_unit_cycle_idx on public.bills (consumer_unit_id, billing_cycle_id, revision desc);
create index bill_components_bill_position_idx on public.bill_components (bill_id, position);
create index reconciliations_org_status_idx on public.reconciliations (organization_id, status);
create index regulatory_rules_lookup_idx on public.regulatory_rules (service, country, state, city, distributor, valid_from desc, priority desc, version desc);
create index regulatory_profiles_unit_rule_idx on public.regulatory_profiles (consumer_unit_id, rule_code, created_at desc);
create index rule_applications_unit_rule_idx on public.rule_applications (consumer_unit_id, regulatory_rule_id, created_at desc);

create or replace function volt_private.prevent_regulatory_rule_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'regulatory_rules are append-only; create a new version instead';
end;
$$;

revoke all on function volt_private.prevent_regulatory_rule_mutation() from public, anon, authenticated;

drop trigger if exists regulatory_rules_append_only on public.regulatory_rules;
create trigger regulatory_rules_append_only
before update or delete on public.regulatory_rules
for each row execute function volt_private.prevent_regulatory_rule_mutation();

alter table public.consumer_units enable row level security;
alter table public.consumer_units force row level security;
alter table public.billing_cycles enable row level security;
alter table public.billing_cycles force row level security;
alter table public.unit_meter_readings enable row level security;
alter table public.unit_meter_readings force row level security;
alter table public.bills enable row level security;
alter table public.bills force row level security;
alter table public.bill_components enable row level security;
alter table public.bill_components force row level security;
alter table public.reconciliations enable row level security;
alter table public.reconciliations force row level security;
alter table public.regulatory_rules enable row level security;
alter table public.regulatory_rules force row level security;
alter table public.regulatory_profiles enable row level security;
alter table public.regulatory_profiles force row level security;
alter table public.rule_applications enable row level security;
alter table public.rule_applications force row level security;

revoke all on public.consumer_units, public.billing_cycles, public.unit_meter_readings,
  public.bills, public.bill_components, public.reconciliations,
  public.regulatory_rules, public.regulatory_profiles, public.rule_applications
from public, anon, authenticated;

grant select, insert, update on public.consumer_units to authenticated;
grant select, insert, update on public.billing_cycles to authenticated;
grant select, insert, update, delete on public.unit_meter_readings to authenticated;
grant usage, select on sequence public.unit_meter_readings_id_seq to authenticated;
grant select, insert, update on public.bills to authenticated;
grant select, insert, update, delete on public.bill_components to authenticated;
grant select, insert, update on public.reconciliations to authenticated;
grant select on public.regulatory_rules to authenticated;
grant select, insert on public.regulatory_profiles to authenticated;
grant select, insert on public.rule_applications to authenticated;

create policy consumer_units_select_org on public.consumer_units
for select to authenticated using ((select volt_private.has_org_access(organization_id)));
create policy consumer_units_insert_org on public.consumer_units
for insert to authenticated with check ((select volt_private.can_write_org(organization_id)) and created_by = (select auth.uid()));
create policy consumer_units_update_org on public.consumer_units
for update to authenticated using ((select volt_private.can_write_org(organization_id)))
with check ((select volt_private.can_write_org(organization_id)));

create policy billing_cycles_select_org on public.billing_cycles
for select to authenticated using ((select volt_private.has_org_access(organization_id)));
create policy billing_cycles_insert_org on public.billing_cycles
for insert to authenticated with check ((select volt_private.can_write_org(organization_id)));
create policy billing_cycles_update_org on public.billing_cycles
for update to authenticated using ((select volt_private.can_write_org(organization_id)))
with check ((select volt_private.can_write_org(organization_id)));

create policy unit_meter_readings_select_org on public.unit_meter_readings
for select to authenticated using ((select volt_private.has_org_access(organization_id)));
create policy unit_meter_readings_insert_org on public.unit_meter_readings
for insert to authenticated with check ((select volt_private.can_write_org(organization_id)) and (created_by is null or created_by = (select auth.uid())));
create policy unit_meter_readings_update_org on public.unit_meter_readings
for update to authenticated using ((select volt_private.can_write_org(organization_id)))
with check ((select volt_private.can_write_org(organization_id)));
create policy unit_meter_readings_delete_org on public.unit_meter_readings
for delete to authenticated using ((select volt_private.can_write_org(organization_id)));

create policy bills_select_org on public.bills
for select to authenticated using ((select volt_private.has_org_access(organization_id)));
create policy bills_insert_org on public.bills
for insert to authenticated with check ((select volt_private.can_write_org(organization_id)));
create policy bills_update_org on public.bills
for update to authenticated using ((select volt_private.can_write_org(organization_id)))
with check ((select volt_private.can_write_org(organization_id)));

create policy bill_components_select_org on public.bill_components
for select to authenticated using ((select volt_private.has_org_access(organization_id)));
create policy bill_components_insert_org on public.bill_components
for insert to authenticated with check ((select volt_private.can_write_org(organization_id)));
create policy bill_components_update_org on public.bill_components
for update to authenticated using ((select volt_private.can_write_org(organization_id)))
with check ((select volt_private.can_write_org(organization_id)));
create policy bill_components_delete_org on public.bill_components
for delete to authenticated using ((select volt_private.can_write_org(organization_id)));

create policy reconciliations_select_org on public.reconciliations
for select to authenticated using ((select volt_private.has_org_access(organization_id)));
create policy reconciliations_insert_org on public.reconciliations
for insert to authenticated with check ((select volt_private.can_write_org(organization_id)));
create policy reconciliations_update_org on public.reconciliations
for update to authenticated using ((select volt_private.can_write_org(organization_id)))
with check ((select volt_private.can_write_org(organization_id)));

create policy regulatory_rules_select_published on public.regulatory_rules
for select to authenticated using (status <> 'draft');

create policy regulatory_profiles_select_org on public.regulatory_profiles
for select to authenticated using ((select volt_private.has_org_access(organization_id)));
create policy regulatory_profiles_insert_org on public.regulatory_profiles
for insert to authenticated with check ((select volt_private.can_write_org(organization_id)));

create policy rule_applications_select_org on public.rule_applications
for select to authenticated using ((select volt_private.has_org_access(organization_id)));
create policy rule_applications_insert_org on public.rule_applications
for insert to authenticated with check ((select volt_private.can_write_org(organization_id)));

comment on table public.consumer_units is 'VOLT: service-specific consumer units. Energy and water never share a unit.';
comment on table public.billing_cycles is 'VOLT: exact billing cycles; civil month is not the primary key.';
comment on table public.unit_meter_readings is 'VOLT: canonical future meter readings keyed by service-specific consumer unit.';
comment on table public.bills is 'VOLT: measured and billed consumption are stored separately.';
comment on table public.bill_components is 'VOLT: structured bill line items with explicit charge/credit direction and provenance.';
comment on table public.regulatory_rules is 'VOLT: append-only, versioned regulatory catalog.';
comment on table public.rule_applications is 'VOLT: links legal rules to billing/reconciliation effects and invoice components.';
