create table if not exists public.monthly_consumption_history (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  consumer_unit_id uuid not null,
  reference_month date not null,
  consumption_kwh numeric not null check (consumption_kwh >= 0),
  consumption_basis text not null default 'billed' check (consumption_basis in ('billed', 'measured', 'not_identified')),
  source_type text not null default 'bill_identified' check (source_type in ('volt_measured', 'user_informed', 'bill_identified', 'volt_calculated', 'rule_predicted')),
  confidence text not null default 'confirmed' check (confidence in ('confirmed', 'probable', 'not_identified')),
  source_bill_id uuid,
  source_label text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint monthly_consumption_history_month_check check (reference_month = date_trunc('month', reference_month)::date),
  constraint monthly_consumption_history_unit_org_fk foreign key (consumer_unit_id, organization_id)
    references public.consumer_units(id, organization_id) on delete cascade,
  constraint monthly_consumption_history_bill_org_fk foreign key (source_bill_id, organization_id)
    references public.bills(id, organization_id) on delete set null,
  unique (consumer_unit_id, reference_month, consumption_basis)
);

create index if not exists monthly_consumption_history_unit_month_idx
  on public.monthly_consumption_history (consumer_unit_id, reference_month desc);

alter table public.monthly_consumption_history enable row level security;
alter table public.monthly_consumption_history force row level security;

revoke all on public.monthly_consumption_history from public, anon, authenticated;
grant select, insert, update, delete on public.monthly_consumption_history to authenticated;
grant usage, select on sequence public.monthly_consumption_history_id_seq to authenticated;

drop policy if exists monthly_consumption_history_select_org on public.monthly_consumption_history;
create policy monthly_consumption_history_select_org on public.monthly_consumption_history
for select to authenticated using ((select volt_private.has_org_access(organization_id)));

drop policy if exists monthly_consumption_history_insert_org on public.monthly_consumption_history;
create policy monthly_consumption_history_insert_org on public.monthly_consumption_history
for insert to authenticated with check (
  (select volt_private.can_write_org(organization_id))
  and (created_by is null or created_by = (select auth.uid()))
);

drop policy if exists monthly_consumption_history_update_org on public.monthly_consumption_history;
create policy monthly_consumption_history_update_org on public.monthly_consumption_history
for update to authenticated using ((select volt_private.can_write_org(organization_id)))
with check ((select volt_private.can_write_org(organization_id)));

drop policy if exists monthly_consumption_history_delete_org on public.monthly_consumption_history;
create policy monthly_consumption_history_delete_org on public.monthly_consumption_history
for delete to authenticated using ((select volt_private.can_write_org(organization_id)));

comment on table public.monthly_consumption_history is 'VOLT: monthly consumption points imported from utility bill history charts. reference_month is a billing reference label, not an inferred meter-reading date.';
comment on column public.monthly_consumption_history.consumption_basis is 'Distinguishes billed consumption from measured consumption; never infer meter readings from monthly billed history.';
